auth_user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.login_user, name="login"),
    path('logout', views.logout_user, name="logout")
]

employee_management/urls.py
from django.contrib import admin  
from django.urls import path, include  
from main.views import index, add, edit, update, destroy

urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('', index, name='home'),
    path('', include('auth_user.urls')),
    path('add',add, name='add'),  
    path('edit/<int:id>', edit, name='edit'),  
    path('update/<int:id>', update, name='update'),  
    path('delete/<int:id>', destroy, name='destroy'),
]  

auth_user/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class UserDetail(models.Model):
    phone = models.CharField(max_length=12)
    iin = models.DecimalField(max_digits=12, decimal_places=0)
    email = models.EmailField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}'

    class Meta:
        verbose_name = 'UserDetail'

main/models.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=15)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "employee"




templates/models.py
from django.db import models

# Create your models here.

auth_user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import UserProfile


class UserForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control form-control-lg form-control-alt'
        self.fields['email'].widget.attrs['class'] = 'form-control form-control-lg form-control-alt'
        self.fields['password1'].widget.attrs['class'] = 'form-control form-control-lg form-control-alt'
        self.fields['password2'].widget.attrs['class'] = 'form-control form-control-lg form-control-alt'

        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class DetailForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(DetailForm, self).__init__(*args, **kwargs)

        self.fields['phone'].widget.attrs['class'] = 'form-control form-control-lg form-control-alt'
        self.fields['iin'].widget.attrs['class'] = 'form-control form-control-lg form-control-alt'
        self.fields['email'].widget.attrs['class'] = 'form-control form-control-lg form-control-alt'

        self.fields['phone'].widget.attrs['placeholder'] = 'Phone'
        self.fields['iin'].widget.attrs['placeholder'] = 'IIN'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'

    class Meta:
        model = UserProfile
        fields = ['phone', 'iin', 'email']

main/forms.py
from django import forms
from django.db.models import query
from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'contact', 'email']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'contact': forms.TextInput(attrs={'class': 'form-control'}),
        }

auth_user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

def login_user(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request=request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                return render(request, 'auth/login.html', {
                    'error': 'Incorrect Username or Password'
                })
        else:
            return render(request, 'auth/login.html')

def logout_user(request):
    logout(request)
    return redirect('login')

main/views.py
from django.shortcuts import render, redirect
from .forms import EmployeeForm
from .models import Employee
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login')
def add(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, 'main/add.html', {'form': form})

@login_required(login_url='/login')
def index(request):
    employees = Employee.objects.all()
    return render(request, "main/index.html", {'employees': employees})

@login_required(login_url='/login')
def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'main/edit.html', {'employee': employee})

@login_required(login_url='/login')
def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect("/")
    return render(request, 'main/edit.html', {'employee': employee})

@login_required(login_url='/login')
def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/")

templates/views.py
from django.shortcuts import render

# Create your views here.

main/templates/main/add.html
{% extends 'main/base.html' %}
 
{% block title %}Add New Employee{% endblock title %}
 
{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form">  
        {% csrf_token %}  
        <div class="container">
            <br>
            <h3 class="mt-2 text-center">How to choose an employee for a company?</h3><br>
            <div class="card-group">
  <div class="card">
    <img src="https://media.istockphoto.com/photos/asian-businesswoman-standing-smiling-at-the-camera-picture-id1335295926?b=1&k=20&m=1335295926&s=170667a&w=0&h=6TEcLiO3JwNG3VL2O1LLWGdFgUulikOMqG1cAGixf-E=" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Hard Skills</h5>
      <p class="card-text">Hard skills are essential because they increase employee productivity and efficiency and subsequently improve employee satisfaction.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img src="https://www.hubspot.com/hubfs/employee-retention-rate.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Soft Skills</h5>
      <p class="card-text">Problem solving, delegating, motivating, and team building are all much easier if you have good soft skills. </p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img src="https://cdn.create.vista.com/api/media/small/153608230/stock-photo-senior-businesswoman-at-workplace" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Critical Thinking</h5>
      <p class="card-text">A person with critical thinking skills can come up with innovative ideas and solutions to complex problems using logic and reason.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
</div>
            <br> 
            <div class="form-group row">  
                <div class="col-sm-4">
                    <br>
                    <h3>Enter Details</h3>
                </div>
            </div>  

            <div class="form-group row">  
                <label class="col-sm-2 col-form-label">Employee Name:</label>  
                <div class="col-sm-4">  
                    {{ form.name }}  
                </div>  
            </div>
            
            <div class="form-group row">  
                <label class="col-sm-2 col-form-label">Employee Email:</label>  
                <div class="col-sm-4">  
                    {{ form.email }}  
                </div>  
            </div>

            <div class="form-group row">  
                <label class="col-sm-2 col-form-label">Employee Contact:</label>  
                <div class="col-sm-4">  
                    {{ form.contact }}  
                </div>  
            </div>

            <div class="form-group row">  
                <div class="col-sm-4">  
                    <button type="submit" class="btn btn-primary">Submit</button>  
                    <a href="{% url 'home'%}"><div class="btn btn-danger">Back</div></a>
                </div>
            </div>

        </div>  
    </form>
<br>
</div> 
{% endblock content %} 

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}    
<html lang="en">
    <head>  
        <meta charset="UTF-8">  
        <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <nav class="navbar navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://newwavestars.eu/wp-content/uploads/2017/08/yellow-star-png-image-yellow-star-png-image-2.png" alt="" width="30" height="24" class="d-inline-block align-text-top">
        <b>Employees Management System</b>
    </a><br>
  </div>
</nav>
    </head>
    <body>
        <div class="container">
            <div class="row">
                {% block content %}{% endblock content %}
            </div>
        </div>

<div class="card bg-dark text-white">
  <img src="https://salahkaarconsultants.com/wp-content/uploads/2017/06/Solving-exam.png" class="card-img" alt="...">
  <div class="card-img-overlay">
    <h5 class="card-title">Contacts</h5><br>
    <p class="card-text">211537@astanait.edu.kz</p>
    <p class="card-text">IA-2101, Astana IT University</p>
  </div>
</div>
        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
        
    </body> 
</html>

main/templates/main/edit.html
{% extends "main/base.html" %}
 
{% block title %}Edit Employee{% endblock title %}
 
{% block content %}

<div class="col-md-12">

<br>
    <h3 class="mt-2 text-center">Update Details</h3>
</div>

    <div class="card" style="width: 39rem; margin-left: auto; margin-right: auto; display: block">
  <img src="https://www.business2community.com/wp-content/uploads/2019/09/small-business-employees-600x336.png" class="card-img-top" alt="...">
</div>

    <form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
        <br>  
        <div class="form-group row">  
            <div class="col-sm-4">
            </div>  
        </div> 
        
        <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Employee Name:</label>  
            <div class="col-sm-4">  
                <input type="text" class="form-control" name="name" id="id_name" required maxlength="100" value="{{ employee.name }}" />  
            </div>  
        </div>  

        <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Employee Email:</label>  
            <div class="col-sm-4">  
                <input type="email" class="form-control" name="email" id="id_email" required maxlength="254" value="{{ employee.email }}" />  
            </div>  
        </div>  

        <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Employee Contact:</label>  
            <div class="col-sm-4">  
                <input type="text" class="form-control" name="contact" id="id_contact" required maxlength="15" value="{{ employee.contact }}" />  
            </div>  
        </div>  

        <div class="form-group row">
            <div class="col-sm-4">  
                    <button type="submit" class="btn btn-success">Update</button>  
                    <a href="{% url 'home'%}"><button class="btn btn-danger mr-3">Back</button>  </a>
            </div>
        </div> 

</div>

</form>
</div>
{% endblock content %}

main/templates/main/index.html

{% extends "main/base.html" %}
 
{% block title %}Employee Records{% endblock title %}
 
{% block content %}

<script>
    $(document).ready(function() {
        $('#dbtable').DataTable();
    } );
</script>


<div class="col-md-12">
<br><br>
    <h3 class="mt-2 text-center">Database</h3>
    <div class="d-flex flex-row justify-content-between">
        <span> 
            <a href="{% url 'add' %}" class="btn btn-primary">Add New Employee</a>
        </span>
        <a href="{% url 'logout'%}"><button class="btn btn-danger mr-3">Sign Out</button>  </a>
        {% comment %} <div class="col-sm-4" style="">  
            
        </div> {% endcomment %}
    </div>
    
    <div class="table-responsive mt-3">
        <table id="dbtable" class="table table-striped table-bordered" width="100%">
            <thead>
                <th>ID</th>
                <th>Employee Name</th>
                <th>Employee Email</th>
                <th>Employee Contact</th>
                <th>Edit</th>
                <th>Delete</th>
            </thead>
            <tbody>
            {% for employee in employees %}
                <tr>  
                    <td>{{ employee.id }}</td>  
                    <td>{{ employee.name }}</td>  
                    <td>{{ employee.email }}</td>  
                    <td>{{ employee.contact }}</td>  
                    <td>
                        <p data-placement="top" data-toggle="tooltip" title="Edit">
                            <a href="/edit/{{ employee.id }}" class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" >
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>
                        </p>
                    </td>
                    <td>
                        <p data-placement="top" data-toggle="tooltip" title="Delete">
                            <a href="/delete/{{ employee.id }}" class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" >
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>
                        </p>
                    </td>  
                </tr>  
            {% endfor %} 
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}